#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long x_a, long long y_a, long long x_b, long long y_b, long long x_c, long long y_c){

}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long x_a;
    std::scanf("%lld", &x_a);
    long long y_a;
    std::scanf("%lld", &y_a);
    long long x_b;
    std::scanf("%lld", &x_b);
    long long y_b;
    std::scanf("%lld", &y_b);
    long long x_c;
    std::scanf("%lld", &x_c);
    long long y_c;
    std::scanf("%lld", &y_c);
    solve(x_a, y_a, x_b, y_b, x_c, y_c);
    return 0;
}
